trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*
pool:
  vmImage: 'Ubuntu-16.04'
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '>=10.x'
    displayName: 'Install Node.js'
  - script: |
      yarn install
    displayName: 'Install Dependencies'
  - script: |
      yarn lint
    displayName: 'Run Linter'
  - script: |
      yarn build
    displayName: 'Build'
  - script: |
      npm install -g vsce
      vsce package -o "texlab.vsix"
    displayName: 'Package'
  - script: |
      vsce publish -p $VSCE_TOKEN --packagePath "texlab.vsix"
    env:
      VSCE_TOKEN: $(vsceToken)
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
    displayName: 'Publish to VS Marketplace'
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: latex-lsp
      repositoryName: latex-lsp/texlab-vscode
      assets: 'texlab.vsix'
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
    displayName: 'Publish to GitHub'
