language: node_js
node_js:
  - node
env:
  global:
    secure: trZ9Y8+mjMEk0e+sLdNZpLckh7ZwtZ9oWAklCs8UYqhP2KQHxxYONoi9exHavPdAGjvEa/Y6hrhLILodtJYcpupburMnd0AFqjWOpRBzK43vZ/gKROo993OTAzrg5qV1eStgP2KH4B8YWVV9iRCWmAE5hGMkzXJgeiO8pT96TVMuiRkuQycoOTPvCzG3yfGY+ksAx8laKmTip7AyVmuEbc6iagHRMEID+ZxYl08TQ3/JVrLhb1NhLobevnWyS77mHhyAW7L7nXtQg1VjlsFKhnugon0VJqzBq9aTV/f1e6+PE1UGsrH5rwn0nI5EoHeS5xC/R3aNgrHC3kviBpXReEXIXMSiEO6I3tywHVGsPuK8wxBlba5W0dDgFKlAfH8ECjrC6ZJj/RnG3AVdfyvZxpBza9NCZYwFpkuLv+OPUHTORYMjfj3Ukrr3nbYylYHdy06Z0RgA2l7N6L3q2/WA3B9x0t+VKmI4V6UDqp/U9fn+Fs6hd6zRfAiN9kGqrm2OcLTuLcKay1VoBmTgIV9lKwILusXr6hM8cKPsiHA5MtnlrGixWIUpc8dikWkN0QDk5hGrIvWIRAdyowcOxk1fNv5ZMCoCVJMMm4o6Ua+RAUwX3h1+XNhqsbi19NEZyvKXYu4jrdul5N7TIdP2K1HAYs1aDPa4azUjUSg10SPy9vc=
cache: yarn
script:
  - yarn compile
  - yarn lint
before_deploy:
  - >
    curl -s https://api.github.com/repos/efoerster/texlab/releases/latest | 
    sed -n 's/.*\(https:\/\/.*\/texlab.jar\).*/\1/p' | 
    wget -qi -'
  - npm install -g vsce
  - vsce package
deploy:
  - provider: releases
    api_key:
      secure: RJ26ec6PqPjvwEyWXfpaDs74b+dq+AQdq9hA0gkwlYmXcGyB7TItkIJfjT+rTC18rd9Cd1OUt4Q276bKyWd/VHU2fXTtRtG7xRL+OxrIQql5YFQFOSu16ySbwFACbp8zKcFcDXWu9WgXUP2vrF3a0dGgCPOfak4KmyVFEh1MYMArAdjErnvaQmar2WTpw1B5FCTUrrkDZquYNh5BcZBI31PcNm5jVKWChTSkPEy23dXsdALHIZnnexAPakWqYr7u9aGlKpAPip+lGoR+5DPPlbkpw+QONdZrzgmf13BjREo2mjJ/ohPRKZo8DaoEMt5dxH9bozT6PQbg05OBMR4d37z3iZz8awUv3nGpNZ71aMRr40vfKQ+3tRsUktePWOWxMcXMXtJtcDxlr/Vb9Wvp73hBQEetJo/I1LhU1y1uNZZg/CGXVSOUzzPITpB9vT0ArutURYAdB3Qe+BGZSETSWghfg/LWJf0AFhVcUcuxSssIwLn9CkaG7C1M7pfgB2qlm64hZHYJzXPbc9KUgukLfWqIxaHWS4xLd/gKZwGLxsuiBzXBVHIZPfEMYiOCpveX88FVxf4NEa0iFI2R1nkFPa7E/NpCnPzNOQhM9INGGaFBFyEWriWv9p+COCDgV1Vig5zveRj1GZ5KLIXolOXithASTwPJXWCzFj/k+Rdwo6E=
    file_glob: true
    file: '*.vsix'
    skip_cleanup: true
    on:
      repo: efoerster/texlab-vscode
      all_branches: true
      tags: true
  - provider: script
    script: vsce publish -p $VSCE_TOKEN
    skip_cleanup: true
    on:
      repo: efoerster/texlab-vscode
      all_branches: true
      tags: true
