name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - uses: samuelmeuli/lint-action@v1
        with:
          eslint: true
          prettier: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
